# Generated by Django 4.0.5 on 2022-06-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_Produit', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_Produit', models.CharField(max_length=50)),
                ('img_Produit', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'db_table': 'Produit',
            },
        ),
    ]
