# Generated by Django 4.0.5 on 2022-06-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivets', '0003_produit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Produits',
        ),
        migrations.AlterModelTable(
            name='produits',
            table='Produits',
        ),
    ]
