# Generated by Django 4.0.5 on 2022-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivets', '0006_produits_slug_alter_produits_img_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boite_au_Lettre',
            fields=[
                ('idBoite', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('nom_Produit', models.CharField(max_length=50)),
                ('img_Produit', models.ImageField(blank=True, null=True, upload_to='products')),
                ('prix_brut', models.FloatField()),
                ('prix_peint', models.FloatField()),
                ('quantite', models.IntegerField()),
            ],
            options={
                'db_table': 'Boite_au_Lettre',
            },
        ),
        migrations.CreateModel(
            name='EMBOUTS',
            fields=[
                ('idBoite', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('nom_Produit', models.CharField(max_length=50)),
                ('img_Produit', models.ImageField(blank=True, null=True, upload_to='products')),
                ('prix_brut', models.FloatField()),
                ('prix_peint', models.FloatField()),
                ('quantite', models.IntegerField()),
            ],
            options={
                'db_table': 'EMBOUTS',
            },
        ),
    ]
