# Generated by Django 4.0.5 on 2022-06-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rivets', '0008_delete_boite_au_lettre_delete_embouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMBOUTS',
            fields=[
                ('idBoite', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('nom_Produit', models.CharField(max_length=50)),
                ('img_Produit', models.ImageField(null=True, upload_to='products')),
                ('prix_brut', models.FloatField()),
                ('prix_peint', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivets.produits')),
            ],
            options={
                'db_table': 'EMBOUTS',
            },
        ),
        migrations.CreateModel(
            name='Boite_au_Lettre',
            fields=[
                ('idBoite', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('nom_Produit', models.CharField(max_length=50)),
                ('img_Produit', models.ImageField(blank=True, null=True, upload_to='products')),
                ('prix_brut', models.FloatField()),
                ('prix_peint', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rivets.produits')),
            ],
            options={
                'db_table': 'Boite_au_Lettre',
            },
        ),
    ]
