# Generated by Django 4.0.5 on 2022-06-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivets', '0009_embouts_boite_au_lettre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embouts',
            name='product',
        ),
        migrations.DeleteModel(
            name='Boite_au_Lettre',
        ),
        migrations.DeleteModel(
            name='EMBOUTS',
        ),
    ]
