# Generated by Django 4.0.1 on 2022-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diametre_corps',
            fields=[
                ('idDiametreCorps', models.IntegerField(primary_key=True, serialize=False)),
                ('diametreCorps', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'db_table': 'diametre_corps',
            },
        ),
        migrations.CreateModel(
            name='Longueur_corps',
            fields=[
                ('idLongueurCorps', models.IntegerField(primary_key=True, serialize=False)),
                ('longueurCorps', models.IntegerField()),
            ],
            options={
                'db_table': 'longueur_corps',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('idMatiere', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Ral',
            fields=[
                ('idRal', models.IntegerField(primary_key=True, serialize=False)),
                ('idTeinte', models.IntegerField()),
                ('idType', models.IntegerField()),
                ('numeroRal', models.IntegerField()),
                ('libelle', models.CharField(max_length=50)),
                ('code_hex', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ral',
            },
        ),
        migrations.CreateModel(
            name='Rivet',
            fields=[
                ('idRivet', models.IntegerField(primary_key=True, serialize=False)),
                ('idMatiereCorps', models.IntegerField()),
                ('idMatiereTige', models.IntegerField()),
                ('idType', models.IntegerField()),
                ('idDiametreCorps', models.IntegerField()),
                ('idLongueurCorps', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prix_brut', models.FloatField()),
                ('prix_peint', models.FloatField()),
            ],
            options={
                'db_table': 'rivet',
            },
        ),
        migrations.CreateModel(
            name='Teinte',
            fields=[
                ('idTeinte', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teinte',
            },
        ),
        migrations.CreateModel(
            name='Type_reference',
            fields=[
                ('idType', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_reference',
            },
        ),
        migrations.CreateModel(
            name='Type_teinte',
            fields=[
                ('idType', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_teinte',
            },
        ),
    ]
