# Generated by Django 4.0.1 on 2022-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_articles_article_articles_diametre_corps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diametre_corps',
            fields=[
                ('idDiametreCorps', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('diametreCorps', models.FloatField(max_length=5)),
            ],
            options={
                'db_table': 'diametre_corps',
            },
        ),
        migrations.CreateModel(
            name='Liste_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReference', models.CharField(max_length=50)),
                ('idType', models.CharField(max_length=50)),
                ('idLongueurCorps', models.CharField(max_length=50)),
                ('idDiametreCorps', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'liste_produit',
            },
        ),
        migrations.CreateModel(
            name='Longueur_corps',
            fields=[
                ('idLongueurCorps', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('longueurCorps', models.FloatField(max_length=5)),
            ],
            options={
                'db_table': 'longueur_corps',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idReference', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='Type_reference',
            fields=[
                ('idType', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_reference',
            },
        ),
        migrations.DeleteModel(
            name='articles',
        ),
    ]
